# Generated by Django 3.2.7 on 2021-09-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
