# Generated by Django 3.2.7 on 2021-09-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_type',
        ),
    ]
